version: "3.9"

services:
  portfolio:
    #image: ghcr.io/elitesalman/astro-portfolio-salman-shafi:latest # Use this ONLY if you want to run Salman Shafi’s official portfolio image exactly as-is
    image: localhost/astro-portfolio
    container_name: portfolio
    init: true
    security_opt:
      - no-new-privileges:true
      - label=type:container_runtime_t
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
      - /tmp:rw,size=128m,mode=0777
    pids_limit: 100
    mem_limit: 1g
    cpus: 1.0
    ports:
      - "4321:4321"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:4321',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
